import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useUser } from "@auth0/nextjs-auth0/client";
import { useRef, useState } from "react";
import Images from "../components/Images";
import LateralBar from "../components/LateralBar";

export default function Home() {
	const { user, error, isLoading } = useUser();
	const [moreInfo, setMoreInfo] = useState(false);
	const profileInfo = useRef<HTMLDivElement>(null);
	const profileImg = useRef<HTMLImageElement>(null);
	const [image, setImg] = useState("");

	typeof window !== "undefined"
		? document.addEventListener("click", function (e) {
				const element: any = e.target;
				if (
					!profileInfo.current?.contains(element) &&
					profileImg.current !== e.target
				) {
					setMoreInfo(false);
				}
		  })
		: "";

	const showMoreInfo = () => {
		setMoreInfo(!moreInfo);
	};

	const saveImages = async (e: any) => {
		const file = e.target.files[0];

		if (file) {
			const reader = new FileReader();
			reader.readAsDataURL(file);

			reader.onload = (event: any) => {
				setImg(event.target.result);
			};
		}

		if (user) {
			//npm i multer
			const newUser: any = { user: user?.email, image: image };
			const res = await fetch("/api/upload", {
				method: "POST",
				body: JSON.stringify(newUser),
			});
			if (res.status && res.status === 201) console.log("subido");
		}
	};

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link
					rel="preconnect"
					href="https://fonts.gstatic.com"
					crossOrigin="anonymous"
				/>
				<link
					href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap"
					rel="stylesheet"
				/>
				<link
					rel="stylesheet"
					href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0"
				/>
			</Head>
			<main className={styles.main}>
				<nav className={styles.nav}>
					<div className={styles.logo}>
						<a href="/">
							GooglePhotos&nbsp;
							<code className={styles.code}>Clone</code>
						</a>
						<div className={styles.searchIcon}>
							<span class="material-symbols-outlined">search</span>

							<input type="text" placeholder="Buscar fotos" />
						</div>
					</div>
					<div className={styles.description}>
						<form encType="multipart/form-data">
							<label>
								<div className={styles.subir}>
									<span class="material-symbols-outlined">upload</span>
									Subir
								</div>

								<input
									type="file"
									multiple
									name="photos"
									id="photos"
									style={{ display: "none" }}
									onChange={(e) => saveImages(e)}
								/>
							</label>
						</form>

						<button>
							<span class="material-symbols-outlined">help</span>
						</button>
						<button>
							<span class="material-symbols-outlined">settings</span>
						</button>
						<button>
							<span class="material-symbols-outlined">apps</span>
						</button>
						{user && (
							<div className={styles.loginButton}>
								<div className={styles.login}>
									<div className={styles.profile} onClick={showMoreInfo}>
										<img
											referrerPolicy="no-referrer"
											ref={profileImg}
											src={user.picture || ""}
											alt="profile picture"
										/>
									</div>
								</div>
							</div>
						)}
						<div className={styles.login}>
							<div>
								{moreInfo && (
									<div ref={profileInfo} className={styles.info}>
										{user && (
											<>
												<div className={styles.profile}>
													<img
														referrerPolicy="no-referrer"
														src={user.picture || ""}
														alt="profile picture"
													/>
												</div>
												<div className={styles.userInfo}>
													<h3>{user.name}</h3>
													<p> {user.email} </p>
												</div>

												<span></span>
												<a className={styles.btn} href="/api/auth/logout">
													<span>Cerrar sesión</span>
												</a>
											</>
										)}
									</div>
								)}
							</div>

							<div>
								{!user && !isLoading && (
									<a className={styles.btn} href="/api/auth/login">
										<span>Login</span>
									</a>
								)}
							</div>
						</div>
					</div>
				</nav>
				<div>
					<LateralBar></LateralBar>
				</div>
				<div className={styles.galleryContainer}>
					<div className={styles.gallery}>
						<Images link="https://picsum.photos/v2/list?page=4&limit=10" />
					</div>
				</div>
			</main>
		</>
	);
}
