import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useUser } from "@auth0/nextjs-auth0/client";
import { useRef, useState } from "react";
import Images from "../components/Images";
import LateralBar from "../components/LateralBar";

export default function Home() {
	const { user, error, isLoading } = useUser();
	const [moreInfo, setMoreInfo] = useState(false);
	const profileInfo = useRef<HTMLDivElement>(null);
	const profileImg = useRef<HTMLImageElement>(null);
	const [images, setImg] = useState("");
	const [showBar, setShowBar] = useState(false);
	const [showInput, setShowInput] = useState(false);

	typeof window !== "undefined"
		? document.addEventListener("click", function (e) {
				const element: any = e.target;
				if (
					!profileInfo.current?.contains(element) &&
					profileImg.current !== e.target
				) {
					setMoreInfo(false);
				}
		  })
		: "";

	const showMoreInfo = () => {
		setMoreInfo(!moreInfo);
	};

	const saveImages = async (e: any) => {
		const file = e.target.files[0];

		if (file) {
			const reader = new FileReader();
			reader.readAsDataURL(file);

			reader.onload = (event: any) => {
				setImg(event.target.result);
			};
		}
		// if (user) {
		// 	npm i multer
		// 	const newUser: any = { user: user?.email, image: image };
		// 	const res = await fetch("/api/upload", {
		// 		method: "POST",
		// 		body: JSON.stringify(newUser),
		// 	});
		// 	if (res.status && res.status === 201) console.log("subido");
		// }
	};

	const showMenu = () => {
		setShowBar(!showBar);
	};

	const showSearch = () => {
		setShowInput(!showInput);
	};

	return (
		<>
			<Head>
				<title>Google Photos Clone</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link
					rel="preconnect"
					href="https://fonts.gstatic.com"
					crossOrigin="anonymous"
				/>
				<link
					href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap"
					rel="stylesheet"
				/>
				<link
					rel="stylesheet"
					href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0"
				/>
			</Head>
			<main className={styles.main}>
				<nav className={styles.nav}>
					<div className={styles.logo}>
						<div className={styles.name}>
							<span className={`${styles.menu}`} onClick={showMenu}>
								<svg
									width="24px"
									height="24px"
									viewBox="0 0 24 24">
									<path d="M3 18h18v-2H3v2zm0-5h18v-2H3v2zm0-7v2h18V6H3z"></path>
								</svg>
							</span>
							<a href="/">
								GooglePhotos&nbsp;
								<code className={styles.code}>Clone</code>
							</a>
						</div>
					</div>
					<div
						className={`${styles.searchIcon} ${
							showInput && styles.showSearch
						}`}>
						<span className="material-symbols-outlined" onClick={showSearch}>
							search
						</span>

						<span className={styles.back} onClick={showSearch}>
							<svg width="24px" height="24px" viewBox="0 0 24 24">
								<path d="M20 11H7.83l5.59-5.59L12 4l-8 8 8 8 1.41-1.41L7.83 13H20v-2z"></path>
							</svg>
						</span>

						<input type="text" placeholder="Buscar fotos" />
					</div>
					<div className={styles.description}>
						<form encType="multipart/form-data">
							<label className={styles.subir} htmlFor="photos">
						
								<span className="material-symbols-outlined">upload</span>

								<label htmlFor="photos">Subir</label>

								<input
									type="file"
									multiple
									name="photos"
									id="photos"
									style={{ display: "none" }}
									onChange={(e) => saveImages(e)}
								/>
							</label>
						</form>

						<button className={styles.help}>
							<span className="material-symbols-outlined">help</span>
						</button>
						<button className={styles.set}>
							<span className="material-symbols-outlined">settings</span>
						</button>
						<button>
							<span className="material-symbols-outlined">apps</span>
						</button>
						{user && (
							<div className={styles.loginButton}>
								<div className={styles.login}>
									<div className={styles.profile} onClick={showMoreInfo}>
										<img
											referrerPolicy="no-referrer"
											ref={profileImg}
											src={user.picture || ""}
											alt="profile picture"
										/>
									</div>
								</div>
							</div>
						)}
						<div className={styles.login}>
							<div>
								{moreInfo && (
									<div ref={profileInfo} className={styles.info}>
										{user && (
											<>
												<div className={styles.profile}>
													<img
														referrerPolicy="no-referrer"
														src={user.picture || ""}
														alt="profile picture"
													/>
												</div>
												<div className={styles.userInfo}>
													<h3>{user.name}</h3>
													<p> {user.email} </p>
												</div>

												<span></span>
												<a className={styles.btn} href="/api/auth/logout">
													<span>Cerrar sesión</span>
												</a>
											</>
										)}
									</div>
								)}
							</div>

							<div>
								{!user && !isLoading && (
									<a className={styles.btn} href="/api/auth/login">
										<span>Login</span>
									</a>
								)}
							</div>
						</div>
					</div>
				</nav>

				<LateralBar showBar={showBar}></LateralBar>

				<div className={styles.galleryContainer}>
					<div className={styles.gallery}>
						<Images
                
							link="https://picsum.photos/v2/list?page=8&limit=7"
							newImagen={images}
						/>
					</div>
				</div>
			</main>
		</>
	);
}
